// packages/luna-svelte/src/component/FieldSet.svelte
<script lang="ts">
  import Group from './Group.svelte'
  import Legend from './Legend.svelte'

  export let title = ''
  export let description = ''
</script>

{#if !title && !description}
  <Group>
    <slot />
  </Group>
{:else}
  <fieldset data-slot="field-set" class="flex flex-col gap-6">
    <Legend {title} {description} />
    <Group>
      <slot />
    </Group>
  </fieldset>
{/if}

// packages/luna-react/src/common/fieldset/index.tsx
import { Group } from '../group'
import { Legend } from '../legend'

export function FieldSet(
  props: Readonly<{
    children?: React.ReactNode
    description?: string
    title?: string
  }>
) {
  if (!props.title && !props.description) {
    return <Group>{props.children}</Group>
  }

  return (
    <fieldset data-slot="set" className="flex flex-col gap-6">
      <Legend title={props.title} description={props.description} />
      <Group>{props.children}</Group>
    </fieldset>
  )
}
