// packages/luna-react/src/component/label.tsx
export function Label(
  props: Readonly<{
    children?: React.ReactNode
    name: string
    required?: boolean
  }>
) {
  return (
    <label
      data-slot="field-label"
      className="flex w-fit items-center gap-2 text-sm leading-snug font-medium select-none"
      htmlFor={props.name}
    >
      {props.children}
      {!props.required && (
        <span className="text-sm text-slate-600 dark:text-slate-400">
          (Optional)
        </span>
      )}
    </label>
  )
}

// packages/luna-svelte/src/component/Label.svelte
<script lang="ts">
  export let name = ''
  export let required = false
</script>

<label
  data-slot="field-label"
  class="flex w-fit items-center gap-2 text-sm leading-snug font-medium select-none"
  for={name}
>
  <slot />
  {#if !required}
    <span class="text-sm text-slate-600 dark:text-slate-400"> (Optional) </span>
  {/if}
</label>
